import json
import os
from pathlib import Path
from datetime import datetime
from ide_analyzer import run_ide_ego_mirror
from git_analyzer import get_git_activity

# Configuration
EGO_MIRROR_ROOT = Path(r"c:\Users\takut\dev\Ego-Mirror")
CANON_ROOT = Path(r"c:\Users\takut\dev\Canon")
REPORT_DIR = EGO_MIRROR_ROOT / "logs" / "reports"

def generate_pov():
    """
    Generate a Proof-of-Value (PoV) report by combining multiple signals.
    """
    print("📢 Ego-Mirror: Generating PoV Report...")
    
    # 1. Collect IDE Stats
    ide_report = run_ide_ego_mirror()
    
    # 2. Collect Git Activity (Last 24h)
    git_stats = get_git_activity(CANON_ROOT)
    
    # 3. Formulate the Report
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_name = f"POV_{timestamp}.md"
    report_path = REPORT_DIR / report_name
    
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(f"# Proof-of-Value Report\n")
        f.write(f"**Timestamp:** {datetime.now().isoformat()}\n")
        f.write(f"**Target System:** Canon Core\n\n")
        
        f.write("## 🛠 AI-Native Activity Summary\n")
        total_ai_turns = sum(ws["stats"]["total_turns"] for ws in ide_report["workspaces"])
        f.write(f"- **Total AI Interactions:** {total_ai_turns}\n")
        
        if ide_report["workspaces"]:
            f.write("### IDE Insights\n")
            for ws in ide_report["workspaces"]:
                stats = ws["stats"]
                f.write(f"- **IDE ({ws['ide']}):** {ws['ws_id'][:8]}...\n")
                f.write(f"  - Troubleshooting: {stats['error_troubleshoot']}\n")
                f.write(f"  - Refactoring: {stats['refactor_request']}\n")
                f.write(f"  - Avg Prompt Density: {stats['avg_user_length']:.1f} chars\n")
        
        f.write("\n## 💻 Engineering Productivity\n")
        f.write(f"- **Commits (Last 24h):** {git_stats.get('commit_count', 0)}\n")
        f.write(f"- **Git Status:** {git_stats.get('stats', 'No activity detected')}\n")
        
        if git_stats.get("commits"):
            f.write("\n### Recent Commit Log\n")
            for c in git_stats["commits"]:
                f.write(f"- `{c}`\n")
                
        f.write("\n\n---\n*Generated by Ego-Mirror AI Awareness Engine.*")
    
    print(f"✅ Report generated: {report_path}")
    return report_path

if __name__ == "__main__":
    generate_pov()
